##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    isaac_usd_path: ""
    usd_path: ""
    usd_robot_root: "/RidgebackFranka"
    usd_flip_joints: ["panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
      "panda_joint6","panda_joint7","panda_finger_joint1", "panda_finger_joint2"]
    usd_flip_joints: {
    "panda_joint1": "Z",
    "panda_joint2": "Z",
    "panda_joint3": "Z",
    "panda_joint4": "Z",
    "panda_joint5": "Z",
    "panda_joint6": "Z",
    "panda_joint7": "Z",
    "panda_finger_joint1": "Y",
    "panda_finger_joint2":  "Y",
    }
    usd_flip_joint_limits: ["panda_finger_joint2"]
    urdf_path: "robot/ridgeback_franka/RidgebackFranka.urdf"
    asset_root_path: "robot/ridgeback_franka"
    base_link: "Root"
    ee_link: "RidgebackFranka_panda_hand"
    # link_names: null
    collision_link_names:
      [
        "Root",
        "RidgebackFranka_panda_link0",
        "RidgebackFranka_panda_link1",
        "RidgebackFranka_panda_link2",
        "RidgebackFranka_panda_link3",
        "RidgebackFranka_panda_link4",
        "RidgebackFranka_panda_link5",
        "RidgebackFranka_panda_link6",
        "RidgebackFranka_panda_link7",
        "RidgebackFranka_panda_hand",
        "RidgebackFranka_panda_leftfinger",
        "RidgebackFranka_panda_rightfinger",
      ]
    collision_spheres: "spheres/ridgeback_mesh_debug.yml"
    collision_sphere_buffer: 0.002 #0.02
    use_global_cumul: True
    self_collision_ignore:
      {
        "base_link": ["RidgebackFranka_panda_link0", "RidgebackFranka_panda_link1", "RidgebackFranka_panda_link2", "RidgebackFranka_panda_link3", "RidgebackFranka_panda_link4"],
        "RidgebackFranka_panda_link0": ["RidgebackFranka_panda_link1", "RidgebackFranka_panda_link2", "Root"],
        "RidgebackFranka_panda_link1": ["RidgebackFranka_panda_link2", "RidgebackFranka_panda_link3", "RidgebackFranka_panda_link4", "Root"],
        "RidgebackFranka_panda_link2": ["RidgebackFranka_panda_link3", "RidgebackFranka_panda_link4", "Root"],
        "RidgebackFranka_panda_link3": ["RidgebackFranka_panda_link4", "RidgebackFranka_panda_link6", "Root"],
        "RidgebackFranka_panda_link4":
          ["RidgebackFranka_panda_link5", "RidgebackFranka_panda_link6", "RidgebackFranka_panda_link7", "RidgebackFranka_panda_link8", "Root"],
        "RidgebackFranka_panda_link5": ["RidgebackFranka_panda_link6", "RidgebackFranka_panda_link7", "RidgebackFranka_panda_hand","RidgebackFranka_panda_leftfinger", "RidgebackFranka_panda_rightfinger", "base_link"],
        "RidgebackFranka_panda_link6": ["RidgebackFranka_panda_link7", "RidgebackFranka_panda_hand",  "RidgebackFranka_panda_leftfinger", "RidgebackFranka_panda_rightfinger"],
        "RidgebackFranka_panda_link7": ["RidgebackFranka_panda_hand", "RidgebackFranka_panda_leftfinger", "RidgebackFranka_panda_rightfinger"],
        "RidgebackFranka_panda_hand": ["RidgebackFranka_panda_leftfinger", "RidgebackFranka_panda_rightfinger"],
        "RidgebackFranka_panda_leftfinger": ["RidgebackFranka_panda_rightfinger"],
        
      }
    
    self_collision_buffer:
      {
        "base_link": 0.0,
        "RidgebackFranka_panda_link0": 0.1, 
        "RidgebackFranka_panda_link1": 0.05, 
        "RidgebackFranka_panda_link2": 0.0,
        "RidgebackFranka_panda_link3": 0.0,
        "RidgebackFranka_panda_link4": 0.0,
        "RidgebackFranka_panda_link5": 0.0,
        "RidgebackFranka_panda_link6": 0.0,
        "RidgebackFranka_panda_link7": 0.0,
        "RidgebackFranka_panda_hand": 0.02,
        "RidgebackFranka_panda_leftfinger": 0.01,
        "RidgebackFranka_panda_rightfinger": 0.01,
      }

    mesh_link_names:
      [
        "base_link",
        "RidgebackFranka_panda_link0",
        "RidgebackFranka_panda_link1",
        "RidgebackFranka_panda_link2",
        "RidgebackFranka_panda_link3",
        "RidgebackFranka_panda_link4",
        "RidgebackFranka_panda_link5",
        "RidgebackFranka_panda_link6",
        "RidgebackFranka_panda_link7",
        "RidgebackFranka_panda_hand",
        "RidgebackFranka_panda_leftfinger",
        "RidgebackFranka_panda_rightfinger",
      ]
    lock_joints: {"panda_finger_joint1": 0.04, "panda_finger_joint2": 0.04}
    cspace:
      joint_names: [
        "dummy_base_prismatic_x_joint", "dummy_base_prismatic_y_joint", "dummy_base_revolute_z_joint",
        "panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
        "panda_joint6","panda_joint7","panda_finger_joint1", "panda_finger_joint2"]
      retract_config: [0, 0, 0, 0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04]
      null_space_weight: [1,1,1,1,1,1,1,1,1,1,1,1]
      cspace_distance_weight: [1,1,1,1,1,1,1,1,1,1,1,1]
      max_acceleration: 15.0 #15.0
      max_jerk: 500.0