##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
collision_spheres:
    Root:
        - "center": [0.23, -0.23, 0.25]
          "radius": 0.23
        - "center": [0.23, 0.23, 0.25]
          "radius": 0.23
        - "center": [-0.23, -0.23, 0.25]
          "radius": 0.23
        - "center": [-0.23, 0.23, 0.25]
          "radius": 0.23
    RidgebackFranka_panda_link0:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.07
        - "center": [0.0, 0.0, 0.2]
          "radius": 0.07
    RidgebackFranka_panda_link1:
        - "center": [0.0, -0.08, 0.0]
          "radius": 0.055
    RidgebackFranka_panda_link2:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.07 
        - "center": [0.0, -0.1, 0.0]
          "radius": 0.07
        - "center": [0.0, -0.2, 0.0]
          "radius": 0.07
        - "center": [0.0, -0.3, 0.0]
          "radius": 0.07 
    RidgebackFranka_panda_link3:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.05
    RidgebackFranka_panda_link4:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.07
        - "center": [0.0, 0.1, 0.07]
          "radius": 0.07
        - "center": [0.0, 0.2, 0.07]
          "radius": 0.07
        - "center": [0.0, 0.3, 0.07]
          "radius": 0.07
    RidgebackFranka_panda_link5:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.07
    RidgebackFranka_panda_link6:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.07
    RidgebackFranka_panda_link7:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.07
    RidgebackFranka_panda_hand:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.03
        - "center": [0.0, 0.06, 0.0]
          "radius": 0.03
        - "center": [0.0, -0.06, 0.0]
          "radius": 0.03
    RidgebackFranka_panda_leftfinger:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.03
    RidgebackFranka_panda_rightfinger:
        - "center": [0.0, -0.0, 0.0]
          "radius": 0.03